contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true 
relativeurls = true
baseurl = "https://github.com/shawnohare/hugo-tufte"
theme = "hugo-tufte"
title = "Hugo-tufte Theme Example Site"

[taxonomies]
  category = "categories" 
  group = "groups"
  series = "series"
  tag = "tags"

[params]
  subtitle = "Subtitle goes here."
  copyrightHolder = "Copyright Holder"
  showPoweredBy = true
  
[params.banner]
  url = "https://i.imgur.com/ON7ulX4.png"
  credit = """\
           You can write quite a long \
           margin-note here, if you like. \
           It will be *mardownified*:  \
           **Give it a whirl!** \
           """

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -100 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Categories"
  pre = "<i class='fa fa-tags fa-lg'></i> "
  weight = -90 
  identifier = "categories"
  url = "/categories"

# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-github fa-2x'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com/shawnohare/hugo-tufte"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-twitter fa-2x'></i> "
  weight = -90 
  identifier = "twitter"
  url = "https://twitter.com"
